get http://localhost:3001/api/persons

###
get http://localhost:3001/api/persons/2

###
delete http://localhost:3001/api/persons/2

###
post http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number": "123-456-7890"
}